[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

# (Optional) You may keep or remove the catch-all /api/* redirect below if you plan to use only Next.js API routes.
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/:splat"
#   status = 200
#   force = true
